package asterisk

import ShopTelephonyConfig
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.Paths
import java.nio.file.StandardCopyOption

/**
 * Writes [content] to [target] atomically: write a temp file in the same directory,
 * then rename over the target. Prevents Asterisk from ever reading a half-written config.
 */
internal fun writeAtomically(target: Path, content: String) {
    Files.createDirectories(target.parent)
    val tmp = Files.createTempFile(target.parent, target.fileName.toString(), ".tmp")
    try {
        Files.writeString(tmp, content)
        makeWorldReadable(tmp)
        Files.move(tmp, target, StandardCopyOption.REPLACE_EXISTING, StandardCopyOption.ATOMIC_MOVE)
    } finally {
        Files.deleteIfExists(tmp)
    }
}

/**
 * createTempFile defaults to mode 600, which the rename preserves — leaving the
 * asterisk user unable to read the result. An unreadable quectel_shops.conf is
 * fatal: the failed #include makes chan_quectel's config load return null and
 * the driver segfaults (observed on the phone server). Force 644.
 */
internal fun makeWorldReadable(file: Path) {
    try {
        Files.setPosixFilePermissions(file, java.nio.file.attribute.PosixFilePermissions.fromString("rw-r--r--"))
    } catch (_: UnsupportedOperationException) {
        // Non-POSIX filesystem (Windows dev machine) — irrelevant there.
    }
}

private const val GENERATED_HEADER =
    ";; GENERATED by ShopBackend — do not edit by hand; changes are overwritten on provisioning.\n"

/**
 * Owns quectel_shops.conf: one chan_quectel (RoEdAl fork) trunk section per shop,
 * regenerated wholesale from the DB on every provisioning run.
 *
 * Server prerequisite (one-time): /etc/asterisk/quectel.conf must contain
 *   #include quectel_shops.conf
 */
class QuectelConfigWriter(private val config: AsteriskConfig, private val amiClient: AmiClient) {

    private val file: Path = Paths.get(config.configPath, "quectel_shops.conf")

    fun regenerate(shops: List<ShopTelephonyConfig>, reload: Boolean = true) {
        val content = buildString {
            append(GENERATED_HEADER)
            for (shop in shops) {
                val device = shop.modemDataDevice?.trim().orEmpty()
                if (device.isEmpty()) continue
                appendLine()
                appendLine("[${config.trunkName(shop.shopId)}]")
                appendLine("data=$device")
                // UAC (USB audio class) voice path — validated on the EC25-EUX fleet.
                appendLine("uac=on")
                shop.modemAlsaDevice?.trim()?.takeIf { it.isNotBlank() }?.let { appendLine("alsadev=$it") }
                appendLine("context=${config.inboundContext(shop.shopId)}")
            }
        }
        writeAtomically(file, content)
        if (reload) amiClient.reloadChanQuectel()
        println("[Asterisk] Wrote $file (${shops.size} trunk(s))")
    }
}

/**
 * Owns extensions_shops.conf: per-shop inbound (GSM → app, GSM SMS → backend) and
 * outbound (app SIP → GSM) dialplan contexts, regenerated wholesale from the DB.
 *
 * Server prerequisites (one-time):
 *   - /etc/asterisk/extensions.conf must contain: #include extensions_shops.conf
 *   - func_curl and JSON_DECODE (res_json / func_json) must be loaded (used to hand
 *     inbound events to the backend over localhost HTTP).
 */
class DialplanWriter(private val config: AsteriskConfig, private val amiClient: AmiClient) {

    private val file: Path = Paths.get(config.configPath, "extensions_shops.conf")

    fun regenerate(shops: List<ShopTelephonyConfig>, reload: Boolean = true) {
        val d = "$"  // avoids Kotlin template/Asterisk ${...} collisions below
        val content = buildString {
            append(GENERATED_HEADER)
            for (shop in shops) {
                if (shop.modemDataDevice.isNullOrBlank()) continue
                val id = shop.shopId
                val trunk = config.trunkName(id)
                val endpoint = config.endpointId(id)
                val base = config.backendBaseUrl
                val secret = config.internalSecret

                appendLine()
                val p = config.promptsPath
                appendLine("[${config.inboundContext(id)}]")
                appendLine("; Inbound GSM call. The backend call/inbound endpoint logs the call and returns a")
                appendLine("; routing verdict: reject | ring | menu_open | menu_closed | menu_temp.")
                appendLine(";   reject      blacklisted caller, or unknown caller while closed  -> hang up (cause 21)")
                appendLine(";   ring        unknown caller while open                           -> ring the app, no prompts")
                appendLine(";   menu_*      known customer                                      -> welcome + DTMF menu")
                appendLine("exten => s,1,NoOp(Inbound call for shop $id from $d{CALLERID(num)})")
                appendLine(" same => n,Set(SHOP_ID=$id)")
                appendLine(" same => n,Set(VERDICT=$d{CURL($base/api/internal/telephony/call/inbound,secret=$secret&shopId=$id&from=$d{URIENCODE($d{CALLERID(num)})}&uniqueid=$d{UNIQUEID})})")
                appendLine(" same => n,GotoIf($d[\"$d{VERDICT}\" = \"reject\"]?rejected,1)")
                appendLine(" same => n,GotoIf($d[\"$d{VERDICT}\" = \"menu_open\"]?welcomeopen,1)")
                appendLine(" same => n,GotoIf($d[\"$d{VERDICT}\" = \"menu_closed\"]?welcomeclosed,1)")
                appendLine(" same => n,GotoIf($d[\"$d{VERDICT}\" = \"menu_temp\"]?welcometemp,1)")
                appendLine(" same => n,Wait(2)")
                appendLine(" same => n,Dial(PJSIP/$endpoint,30)")
                appendLine(" same => n,Hangup()")
                appendLine()
                appendLine("exten => rejected,1,Hangup(21)")
                appendLine()
                appendLine("; Known customer: answer, play the shop's welcome, then run the DTMF menu.")
                appendLine("exten => welcomeopen,1,Answer()")
                appendLine(" same => n,Wait(1)")
                appendLine(" same => n,Playback($p/shop$id-welcome-open)")
                appendLine(" same => n,Goto(menuopen,1)")
                appendLine("exten => welcomeclosed,1,Answer()")
                appendLine(" same => n,Wait(1)")
                appendLine(" same => n,Playback($p/shop$id-welcome-closed)")
                appendLine(" same => n,Goto(menuclosed,1)")
                appendLine("; Temporary operator closure during open hours: open welcome, closed menu (no operator option).")
                appendLine("exten => welcometemp,1,Answer()")
                appendLine(" same => n,Wait(1)")
                appendLine(" same => n,Playback($p/shop$id-welcome-open)")
                appendLine(" same => n,Goto(menuclosed,1)")
                appendLine()
                appendLine("; Menu while open: 1 = SMS booking link, 2 = operator (the manager app). 3 attempts.")
                appendLine("exten => menuopen,1,Set(ATTEMPT=1)")
                appendLine(" same => n(prompt),Read(DIGIT,$p/shop$id-menu-open,1,,1,15)")
                appendLine(" same => n,GotoIf($d[\"$d{DIGIT}\" = \"1\"]?smslink,1)")
                appendLine(" same => n,GotoIf($d[\"$d{DIGIT}\" = \"2\"]?operator,1)")
                appendLine(" same => n,Set(ATTEMPT=$d[$d{ATTEMPT} + 1])")
                appendLine(" same => n,GotoIf($d[$d{ATTEMPT} <= 3]?prompt)")
                appendLine(" same => n,Goto(menutimeout,1)")
                appendLine()
                appendLine("; Menu while closed/temp-closed: only 1 = SMS booking link. 3 attempts.")
                appendLine("exten => menuclosed,1,Set(ATTEMPT=1)")
                appendLine(" same => n(prompt),Read(DIGIT,$p/shop$id-menu-closed,1,,1,15)")
                appendLine(" same => n,GotoIf($d[\"$d{DIGIT}\" = \"1\"]?smslink,1)")
                appendLine(" same => n,Set(ATTEMPT=$d[$d{ATTEMPT} + 1])")
                appendLine(" same => n,GotoIf($d[$d{ATTEMPT} <= 3]?prompt)")
                appendLine(" same => n,Goto(menutimeout,1)")
                appendLine()
                appendLine("exten => menutimeout,1,Set(EVT=$d{CURL($base/api/internal/telephony/call/event,secret=$secret&uniqueid=$d{UNIQUEID}&event=menu_timeout)})")
                appendLine(" same => n,Playback($p/menu-invalid-goodbye)")
                appendLine(" same => n,Hangup()")
                appendLine()
                appendLine("; Digit 1: backend creates a booking token and texts the link via this shop's SIM.")
                appendLine("exten => smslink,1,Set(SMSRESULT=$d{CURL($base/api/internal/telephony/booking-link,secret=$secret&shopId=$id&from=$d{URIENCODE($d{CALLERID(num)})}&uniqueid=$d{UNIQUEID})})")
                appendLine(" same => n,GotoIf($d[\"$d{SMSRESULT}\" = \"ok\"]?sent)")
                appendLine(" same => n,Playback($p/sms-failed)")
                appendLine(" same => n,Hangup()")
                appendLine(" same => n(sent),Playback($p/sms-sent)")
                appendLine(" same => n,Hangup()")
                appendLine()
                appendLine("; Digit 2: ring the manager app.")
                appendLine("exten => operator,1,Set(EVT=$d{CURL($base/api/internal/telephony/call/event,secret=$secret&uniqueid=$d{UNIQUEID}&event=operator)})")
                appendLine(" same => n,Dial(PJSIP/$endpoint,30)")
                appendLine(" same => n,Playback($p/operator-unavailable)")
                appendLine(" same => n,Hangup()")
                appendLine("; Inbound SMS: chan_quectel delivers body as JSON in \${SMS}; forward to backend.")
                appendLine("exten => sms,1,NoOp(Inbound SMS for shop $id from $d{CALLERID(num)})")
                appendLine(" same => n,Set(SMS_BODY=$d{JSON_DECODE(SMS,msg)})")
                appendLine(" same => n,Set(NOTIFY_RESULT=$d{CURL($base/api/internal/telephony/sms/inbound,secret=$secret&shopId=$id&from=$d{URIENCODE($d{CALLERID(num)})}&body=$d{URIENCODE($d{SMS_BODY})})})")
                appendLine(" same => n,Hangup()")
                appendLine()
                appendLine("[${config.outboundContext(id)}]")
                appendLine("; Outbound call from the manager app via this shop's SIM.")
                appendLine("exten => _+X.,1,Dial(Quectel/$trunk/$d{EXTEN},60)")
                appendLine(" same => n,Hangup()")
                appendLine("exten => _0X.,1,Dial(Quectel/$trunk/$d{EXTEN},60)")
                appendLine(" same => n,Hangup()")
            }
        }
        writeAtomically(file, content)
        if (reload) amiClient.reloadDialplan()
        println("[Asterisk] Wrote $file (${shops.size} shop context set(s))")
    }
}
