package asterisk

import ShopTelephonyConfig
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.Paths
import java.nio.file.StandardCopyOption

/**
 * Writes [content] to [target] atomically: write a temp file in the same directory,
 * then rename over the target. Prevents Asterisk from ever reading a half-written config.
 */
internal fun writeAtomically(target: Path, content: String) {
    Files.createDirectories(target.parent)
    val tmp = Files.createTempFile(target.parent, target.fileName.toString(), ".tmp")
    try {
        Files.writeString(tmp, content)
        Files.move(tmp, target, StandardCopyOption.REPLACE_EXISTING, StandardCopyOption.ATOMIC_MOVE)
    } finally {
        Files.deleteIfExists(tmp)
    }
}

private const val GENERATED_HEADER =
    ";; GENERATED by ShopBackend — do not edit by hand; changes are overwritten on provisioning.\n"

/**
 * Owns quectel_shops.conf: one chan_quectel (RoEdAl fork) trunk section per shop,
 * regenerated wholesale from the DB on every provisioning run.
 *
 * Server prerequisite (one-time): /etc/asterisk/quectel.conf must contain
 *   #include quectel_shops.conf
 */
class QuectelConfigWriter(private val config: AsteriskConfig, private val amiClient: AmiClient) {

    private val file: Path = Paths.get(config.configPath, "quectel_shops.conf")

    fun regenerate(shops: List<ShopTelephonyConfig>, reload: Boolean = true) {
        val content = buildString {
            append(GENERATED_HEADER)
            for (shop in shops) {
                val device = shop.modemDataDevice?.trim().orEmpty()
                if (device.isEmpty()) continue
                appendLine()
                appendLine("[${config.trunkName(shop.shopId)}]")
                appendLine("data=$device")
                // UAC (USB audio class) voice path — validated on the EC25-EUX fleet.
                appendLine("uac=on")
                shop.modemAlsaDevice?.trim()?.takeIf { it.isNotBlank() }?.let { appendLine("alsadev=$it") }
                appendLine("context=${config.inboundContext(shop.shopId)}")
            }
        }
        writeAtomically(file, content)
        if (reload) amiClient.reloadChanQuectel()
        println("[Asterisk] Wrote $file (${shops.size} trunk(s))")
    }
}

/**
 * Owns extensions_shops.conf: per-shop inbound (GSM → app, GSM SMS → backend) and
 * outbound (app SIP → GSM) dialplan contexts, regenerated wholesale from the DB.
 *
 * Server prerequisites (one-time):
 *   - /etc/asterisk/extensions.conf must contain: #include extensions_shops.conf
 *   - func_curl and JSON_DECODE (res_json / func_json) must be loaded (used to hand
 *     inbound events to the backend over localhost HTTP).
 */
class DialplanWriter(private val config: AsteriskConfig, private val amiClient: AmiClient) {

    private val file: Path = Paths.get(config.configPath, "extensions_shops.conf")

    fun regenerate(shops: List<ShopTelephonyConfig>, reload: Boolean = true) {
        val d = "$"  // avoids Kotlin template/Asterisk ${...} collisions below
        val content = buildString {
            append(GENERATED_HEADER)
            for (shop in shops) {
                if (shop.modemDataDevice.isNullOrBlank()) continue
                val id = shop.shopId
                val trunk = config.trunkName(id)
                val endpoint = config.endpointId(id)
                val base = config.backendBaseUrl
                val secret = config.internalSecret

                appendLine()
                appendLine("[${config.inboundContext(id)}]")
                appendLine("; Inbound GSM call: notify backend (call log + routing decision), give the app a moment to wake, then ring it.")
                appendLine("; The backend answers \"reject\" for blacklisted callers and closed shops; anything else rings the app.")
                appendLine("exten => s,1,NoOp(Inbound call for shop $id from $d{CALLERID(num)})")
                appendLine(" same => n,Set(SHOP_ID=$id)")
                appendLine(" same => n,Set(NOTIFY_RESULT=$d{CURL($base/api/internal/telephony/call/inbound,secret=$secret&shopId=$id&from=$d{URIENCODE($d{CALLERID(num)})}&uniqueid=$d{UNIQUEID})})")
                appendLine(" same => n,GotoIf($d[\"$d{NOTIFY_RESULT}\" = \"reject\"]?rejected)")
                appendLine(" same => n,Wait(2)")
                appendLine(" same => n,Dial(PJSIP/$endpoint,30)")
                appendLine(" same => n,Hangup()")
                appendLine(" same => n(rejected),Hangup(21)")
                appendLine("; Inbound SMS: chan_quectel delivers body as JSON in \${SMS}; forward to backend.")
                appendLine("exten => sms,1,NoOp(Inbound SMS for shop $id from $d{CALLERID(num)})")
                appendLine(" same => n,Set(SMS_BODY=$d{JSON_DECODE(SMS,msg)})")
                appendLine(" same => n,Set(NOTIFY_RESULT=$d{CURL($base/api/internal/telephony/sms/inbound,secret=$secret&shopId=$id&from=$d{URIENCODE($d{CALLERID(num)})}&body=$d{URIENCODE($d{SMS_BODY})})})")
                appendLine(" same => n,Hangup()")
                appendLine()
                appendLine("[${config.outboundContext(id)}]")
                appendLine("; Outbound call from the manager app via this shop's SIM.")
                appendLine("exten => _+X.,1,Dial(Quectel/$trunk/$d{EXTEN},60)")
                appendLine(" same => n,Hangup()")
                appendLine("exten => _0X.,1,Dial(Quectel/$trunk/$d{EXTEN},60)")
                appendLine(" same => n,Hangup()")
            }
        }
        writeAtomically(file, content)
        if (reload) amiClient.reloadDialplan()
        println("[Asterisk] Wrote $file (${shops.size} shop context set(s))")
    }
}
