#!/usr/bin/env python3
"""Time a TCP SYN -> RST round trip to a closed port on a tailnet peer.
The RST is generated by the peer's tailnet netstack, NOT by the app, so this
measures the TCP-layer cost of the DERP relay with the application excluded --
the exact counterpart to an ICMP echo over the same path."""
import socket, sys, time
ip = sys.argv[1]; port = int(sys.argv[2]) if len(sys.argv) > 2 else 9
n = int(sys.argv[3]) if len(sys.argv) > 3 else 8
rtts = []
for _ in range(n):
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM); s.settimeout(5.0)
    t0 = time.monotonic()
    try:
        s.connect((ip, port)); rtts.append((time.monotonic()-t0)*1000)  # accepted
    except ConnectionRefusedError:
        rtts.append((time.monotonic()-t0)*1000)                         # RST = a full round trip
    except (socket.timeout, OSError):
        pass
    finally:
        s.close()
    time.sleep(0.3)
if rtts:
    rtts.sort()
    print(f"  TCP  n={len(rtts)}/{n} min={rtts[0]:.0f} med={rtts[len(rtts)//2]:.0f} max={rtts[-1]:.0f} ms")
else:
    print(f"  TCP  n=0/{n} (no RST - port filtered, not closed)")
