# .platform.app.yaml
name: shopbackend
type: "docker:17"
disk: 1024

# Environment variables
variables:
  env:
    JAVA_HOME: "/usr/lib/jvm/java-17-openjdk"

# Declare persistent storage for SQLite
mounts:
  "/data": "shared:files"

relationships: {}

hooks:
  build: |
    echo "Using Docker-based app; build handled by Dockerfile"
