applications:
  shopbackend:
    type: "docker:17"
    disk: 1024

    # Environment variables
    variables:
      env:
        JAVA_HOME: "/usr/lib/jvm/java-17-openjdk"

    # Persistent storage for SQLite
    mounts:
      "/data": "shared:files"

    # Build hook (optional, here just logs)
    hooks:
      build: |
        echo "Building Docker-based ShopBackend app..."

routes:
  main:
    type: upstream
    upstream: "shopbackend:http"
    url: "https://{default}/"

  api:
    type: upstream
    upstream: "shopbackend:http"
    url: "https://{default}/api/"

  mobile:
    type: upstream
    upstream: "shopbackend:http"
    url: "https://{default}/mobile/"
