# .upsun/config.yaml
# Upsun / platform-style configuration
# Top-level keys must be one of: applications, services, or routes

applications:
  shopbackend:
    # type can be 'docker' or 'php' etc. Use docker here if you build an image, otherwise leave generic.
    type: "generic"
    disk: 1024
    environment:
      JAVA_HOME: "/usr/lib/jvm/java-17-openjdk"

    # Build hooks: run your Gradle build here and produce the dist/ShopBackend.jar artifact.
    hooks:
      build: |
        set -euo pipefail
        chmod +x ./gradlew || true
        ./gradlew --no-daemon clean build -x test
        mkdir -p dist
        # copy the fat jar if present, otherwise the regular jar
        cp build/libs/*-all.jar dist/ShopBackend.jar || cp build/libs/*.jar dist/ShopBackend.jar

    # artifacts that will be uploaded from the built repo
    artifacts:
      - src: dist/ShopBackend.jar
        dest: /artifacts/ShopBackend.jar

    # optional relationships or services can be declared here if needed
    relationships: {}

# Routes: map public paths to internal ports. Adjust domains/paths as needed for your environment.
routes:
  src: "https://{default}/"
  dest: "http://localhost:9090"
  src: "https://{default}/api/"
  dest: "http://localhost:9091"
  src: "https://{default}/mobile/"
  dest: "http://localhost:9092"

# Optional cache entries (keep Gradle caches)
cache:
  - .gradle
  - ~/.gradle
