# .upsun/config.yaml

applications:
  shopbackend:
    type: "java:17"

    # Optional: if your code isn't at repo root, set the source root
    # source:
    #   root: "/"

    variables:
      env:
        JAVA_HOME: "/usr/lib/jvm/java-17-openjdk"

    # Writable, persistent storage (e.g., for file uploads, SQLite, etc.)
    mounts:
      "data":
        source: storage
        source_path: "data"

    # Build your jar once during the build phase.
    hooks:
     build: |
       set -eu
       chmod +x ./gradlew || true
       ./gradlew --no-daemon clean shadowJar -x test

    web:
      commands:
      # Ktor reads these system properties; host ensures it binds externally.
      start: 'java -Dktor.deployment.host=0.0.0.0 -Dktor.deployment.port=$PORT -jar dist/ShopBackend.jar --db=/data/ShopManager.db'

      # If you also serve static files directly, you can add locations here.
      # locations:
      #   "/":
      #     passthru: true

# Routes: each key is the public URL; route to the app's HTTP upstream.
routes:
  "https://{default}/":
    type: upstream
    upstream: "shopbackend:http"

  "https://{default}/api/":
    type: upstream
    upstream: "shopbackend:http"

  "https://{default}/mobile/":
    type: upstream
    upstream: "shopbackend:http"
