# .upsun/config.yaml

applications:
  shopbackend:
    type: "java:17"

    # Optional: if your code isn't at repo root, set the source root
    # source:
    #   root: "/"

    variables:
      env:
        JAVA_HOME: "/usr/lib/jvm/java-17-openjdk"

    # Writable, persistent storage (e.g., for file uploads, SQLite, etc.)
    mounts:
      "data":
        source: storage
        source_path: "data"

    # Build your jar once during the build phase.
    hooks:
      build: |
        set -euo pipefail
        chmod +x ./gradlew || true
        ./gradlew --no-daemon clean build -x test
        # Copy the built JAR to a stable filename so the start command is simple.
        cp build/libs/*-all.jar app.jar || cp build/libs/*.jar app.jar

    # How the app is served
    web:
      commands:
        # Expose your app on the port provided by Upsun ($PORT).
        # For Spring Boot, --server.port=$PORT works; for other frameworks set their port option.
        start: |
          java -jar app.jar --server.port=$PORT

      # If you also serve static files directly, you can add locations here.
      # locations:
      #   "/":
      #     passthru: true

# Routes: each key is the public URL; route to the app's HTTP upstream.
routes:
  "https://{default}/":
    type: upstream
    upstream: "shopbackend:http"

  "https://{default}/api/":
    type: upstream
    upstream: "shopbackend:http"

  "https://{default}/mobile/":
    type: upstream
    upstream: "shopbackend:http"
