"https://{default}/":
  type: upstream
  upstream: "shopbackend:http"

"https://{default}/api/":
  type: upstream
  upstream: "shopbackend:http"

"https://{default}/mobile/":
  type: upstream
  upstream: "shopbackend:http"

"https://www.{default}/":
  type: redirect
  to: "https://{default}/"
